### PR TITLE
Adding autoware on f1tenth section

### PR DESCRIPTION
**Pull request by jetag**
This PR adds the necessary documentation for Autoware Installation on Jetson Xavier NX and also includes a F1tenth Record-Replay Demo.

### CODE REVIEW

**Review by hzheng40 — APPROVED** [review]
lg

**Comment by hzheng40** [comment]
@jetag there are a few syntax errors, pls fix.
See [https://f1tenth.readthedocs.io/en/foxy_test/autoware/intro.html](https://f1tenth.readthedocs.io/en/foxy_test/autoware/intro.html) for the build. Try to build locally to check.

**Comment by jetag** [comment]
Okay on it

**Comment by jetag** [comment]
Okay on it

**Pull request merged**
